version: '3.1'
services:
  speedtest-exporter:
    restart: always
    #build: .
    image: ghcr.io/sk2sat/twitter-exporter/twitter-exporter:main
    ports:
      - 9103:9103
    volumes:
      - ./config.toml:/app/config.toml
